#!/bin/sh
set -e

if dpkg-statoverride --list /usr/bin/crontab > /dev/null ; then
	dpkg-statoverride --remove /usr/bin/crontab
fi

# Automatically added by dh_installinit/13.24.1ubuntu2
if [ "$1" = "remove" ] && [ -x "/etc/init.d/dcron" ] ; then
	chmod -x "/etc/init.d/dcron" >/dev/null || true
fi
if [ -z "$DPKG_ROOT" ] && [ "$1" = "purge" ] ; then
	update-rc.d dcron remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.24.1ubuntu2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.24.1ubuntu2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'dcron.service' >/dev/null || true
	fi
fi
# End automatically added section

