#!/bin/sh
set -e

# Automatically added by dh_installinit/13.24.1ubuntu2
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/dcron" ] ; then
	chmod +x "/etc/init.d/dcron" >/dev/null || true
fi
# End automatically added section

