#!/bin/sh
set -e

# Automatically added by dh_installinit/13.24.1ubuntu2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -x "/etc/init.d/dcron" ] ; then
	invoke-rc.d dcron stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.24.1ubuntu2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'dcron.service' >/dev/null || true
fi
# End automatically added section

